name: Tests

on:
  workflow_run:
    workflows: ['Quality']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Jest
        path: '*.xml'
        reporter: jest-junit